# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Electric Networks Forum

# Short description (goes below the title; it will also be used in the RSS feed)
description: The Forum for everything Electric Networks.

# Your name, as you want it to appear underneath each post and in the footer
author: Electric Networks

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
baseurl: /

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://electricnetworks.github.io

# Exclude system files
exclude: [.gitignore]

# The disqus shortname for your forum
disqus_shortname: electricnetworks 
# The public key for your disqus application
disqus_publickey: hGoUPPNTbDEc8POYJ1RBsoK32Q8rGHYlGbMbzm47ysWMci59b3VI4y2UUPHmuXpu